Refactor abstract tree node
grahaminn/AIinGames-Assignment1 pull request #4
Opened 2023-10-15 11:46 UTC by nocommentcode

Refactored the abstract class `TreeNode`

There was an issue with the previous refactoring. The `TreeNode` class now handles the outer loop of checking all children.
This will make implemeting different Tree Policies even easier

2023-10-17 12:58 UTC, grahaminn requested changes
Noted additional place to rename

2023-10-17 12:58 UTC, grahaminn commented on src/main/java/groupM/players/mcts/MCTSPlayer.java
>      public MCTSPlayer(long seed) {
Rename here?

2023-10-17 12:58 UTC, grahaminn commented on src/main/java/groupM/players/mcts/MCTSPlayer.java
>      public MCTSPlayer(MCTSParams params) {
Ditto

2023-10-17 13:23 UTC, grahaminn commented on src/main/java/groupM/players/mcts/TreeNode.java
> +        UCB1TreeNode child = (UCB1TreeNode) children.get(action);
What's the relationship between TreeNode and UCB1TreeNode? Should TreeNode assume it's children are of type UCBTreeNode?

2023-10-17 15:11 UTC, pranigopu approved these changes

2023-10-18 11:44 UTC, grahaminn approved these changes
lgtm

2023-10-18 11:44 UTC, merged